'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const main = fs.readFileSync(path.join(__dirname, 'main.cjs'), 'utf8')
const sessions = fs.readFileSync(path.join(__dirname, 'browser-sessions.cjs'), 'utf8')
const provider = fs.readFileSync(path.join(__dirname, 'browser-provider.cjs'), 'utf8')
const codeServer = fs.readFileSync(path.join(__dirname, 'code-server-manager.cjs'), 'utf8')
const preload = fs.readFileSync(path.join(__dirname, 'preload.cjs'), 'utf8')

test('desktop composes a secure trusted WebContentsView in a BaseWindow', () => {
  assert.match(main, /new BaseWindow\(/)
  assert.match(main, /new WebContentsView\(/)
  assert.match(main, /preload: preloadPath/)
  assert.match(main, /contextIsolation: true/)
  assert.match(main, /nodeIntegration: false/)
  assert.match(main, /sandbox: true/)
  assert.match(main, /event\.senderFrame !== contents\.mainFrame/)
  assert.match(main, /requireLoopbackHttpUrl/)
  assert.doesNotMatch(main, /new BrowserWindow\(/)
})

test('guest tabs are isolated WebContentsViews with no preload or Node integration', () => {
  assert.match(sessions, /new this\.WebContentsView\(/)
  assert.match(sessions, /partition: this\.partition/)
  assert.match(sessions, /contextIsolation: true/)
  assert.match(sessions, /nodeIntegration: false/)
  assert.match(sessions, /disableDialogs: true/)
  assert.match(sessions, /sandbox: true/)
  assert.doesNotMatch(sessions, /preload:/)
  assert.doesNotMatch(sessions, /persist:/)
})

test('guest policy denies permissions, downloads, protected origins, and native popups', () => {
  assert.match(sessions, /setPermissionCheckHandler\(\(\) => false\)/)
  assert.match(sessions, /setPermissionRequestHandler/)
  assert.match(sessions, /will-download/)
  assert.match(sessions, /event\.preventDefault\(\)/)
  assert.match(sessions, /webRequest\.onBeforeRequest/)
  assert.match(sessions, /setWindowOpenHandler/)
  assert.match(sessions, /return \{ action: 'deny' \}/)
})

test('browser control uses the WebContents debugger and real CDP input', () => {
  assert.match(sessions, /debug\.attach\(DEBUGGER_PROTOCOL_VERSION\)/)
  assert.match(sessions, /debug\.sendCommand\(method, params\)/)
  assert.match(sessions, /Input\.dispatchMouseEvent/)
  assert.match(sessions, /Input\.insertText/)
  assert.match(sessions, /Accessibility\.getFullAXTree/)
  assert.match(sessions, /Page\.captureScreenshot/)
  assert.match(sessions, /DOM\.setFileInputFiles/)
  assert.match(sessions, /ALLOWED_CDP_DOMAINS/)
  assert.doesNotMatch(main + sessions, /remote-debugging-port/)
})

test('provider uses an authenticated dynamic loopback listener and secure atomic config', () => {
  assert.match(provider, /host: '127\.0\.0\.1', port: 0/)
  assert.match(provider, /randomBytes\(32\)\.toString\('hex'\)/)
  assert.match(provider, /DIRE_MUX_BROWSER_PROVIDER_CONFIG/)
  assert.match(provider, /DIRE_MUX_DATA_DIR/)
  assert.match(provider, /'wx', 0o600/)
  assert.match(provider, /Authorization|authorization/)
  assert.match(provider, /requestUrl\.pathname !== '\/v1\/action'/)
})

test('Code uses a separately sandboxed WebContentsView and private loopback code-server', () => {
  assert.match(main, /new CodeServerWorkspaceManager\(/)
  assert.match(codeServer, /new this\.WebContentsView\(/)
  assert.match(codeServer, /partition: CODE_SERVER_PARTITION/)
  assert.doesNotMatch(codeServer, /persist:/)
  assert.match(codeServer, /contextIsolation: true/)
  assert.match(codeServer, /nodeIntegration: false/)
  assert.match(codeServer, /disableDialogs: true/)
  assert.match(codeServer, /sandbox: true/)
  assert.doesNotMatch(codeServer, /preload:/)
  assert.match(codeServer, /'--bind-addr', '127\.0\.0\.1:0'/)
  assert.match(codeServer, /'--auth', 'password'/)
  assert.match(codeServer, /PASSWORD: password/)
  assert.match(codeServer, /setPermissionRequestHandler/)
  assert.match(codeServer, /webRequest\.onBeforeRequest/)
})

test('preload exposes only the narrow native view APIs', () => {
  assert.match(preload, /exposeInMainWorld\('direMuxDesktopBrowser'/)
  assert.match(preload, /show\(options\)/)
  assert.match(preload, /hide\(options\)/)
  assert.match(preload, /setBounds\(options\)/)
  assert.match(preload, /setBackendOrigin\(origin\)/)
  assert.match(preload, /ipcRenderer\.invoke\(browserChannels\.setBackendOrigin, origin\)/)
  assert.match(preload, /onState\(callback\)/)
  assert.match(preload, /onWorkspaceShortcut\(callback\)/)
  assert.match(preload, /exposeInMainWorld\('direMuxDesktopCodeServer'/)
  assert.match(preload, /close\(options\)/)
  assert.match(preload, /process\.isMainFrame/)
  assert.doesNotMatch(preload, /exposeInMainWorld\([^\n]+ipcRenderer/)
  assert.match(main, /validateBackendOrigin/)
  assert.match(main, /setRendererBackendOrigin/)
  assert.match(main, /codeServerWorkspace\?\.addProtectedOrigin\(origin\)/)
})
