#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes("--check");
const marker = "/* DIRE_MUX_SHARED_COMMON */";
const shared = (await readFile(join(root, "common.shared.mjs"), "utf8")).trim();
const targets = [
  ["common.processes.mjs.tmpl", "kiwi-code-processes/scripts/common.mjs"],
  ["common.threads.mjs.tmpl", "dire-mux-threads/scripts/common.mjs"],
];

let stale = false;
for (const [templateName, targetName] of targets) {
  const template = await readFile(join(root, templateName), "utf8");
  if (template.split(marker).length !== 2) {
    throw new Error(`${templateName} must contain ${marker} exactly once`);
  }
  const output = [
    "// Code generated by generate-common.mjs; DO NOT EDIT.",
    "",
    template.replace(
      marker,
      `// BEGIN SHARED COMMON\n${shared}\n// END SHARED COMMON`,
    ).trim(),
    "",
  ].join("\n");
  const target = join(root, targetName);
  if (check) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== output) {
      console.error(`${targetName} is stale; run node internal/server/agent-skill/generate-common.mjs`);
      stale = true;
    }
  } else {
    await writeFile(target, output);
  }
}

if (stale) process.exitCode = 1;
