package server

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestAgentSkillInstallerInstallsAndUpdatesBundle(t *testing.T) {
	installer := newAgentSkillInstaller(filepath.Join(t.TempDir(), ".agents", "skills"))

	status, err := installer.status()
	if err != nil {
		t.Fatal(err)
	}
	if status.Installed || status.UpToDate {
		t.Fatalf("unexpected initial status: %#v", status)
	}
	if filepath.Base(status.Path) != agentSkillName {
		t.Fatalf("skill path = %q", status.Path)
	}
	if len(status.Skills) != len(bundledAgentSkillNames) {
		t.Fatalf("skill statuses = %#v", status.Skills)
	}

	status, err = installer.install()
	if err != nil {
		t.Fatal(err)
	}
	if !status.Installed || !status.UpToDate {
		t.Fatalf("unexpected installed status: %#v", status)
	}
	contents, err := os.ReadFile(filepath.Join(status.Path, "SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"name: dire-mux-processes",
		"scripts/start-process.mjs",
		"scripts/read-logs.mjs",
	} {
		if !strings.Contains(string(contents), expected) {
			t.Fatalf("SKILL.md does not contain %q", expected)
		}
	}
	if info, err := os.Stat(filepath.Join(status.Path, "scripts", "start-process.mjs")); err != nil {
		t.Fatal(err)
	} else if info.Mode()&0o111 == 0 {
		t.Fatalf("start-process.mjs mode = %v, want executable", info.Mode())
	}
	threadsPath := filepath.Join(filepath.Dir(status.Path), "dire-mux-threads")
	threadSkill, err := os.ReadFile(filepath.Join(threadsPath, "SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"name: dire-mux-threads",
		"scripts/create-thread.mjs",
		"scripts/archive-thread.mjs",
		"scripts/close-thread.mjs",
		"scripts/read-tmux-lines.mjs",
		"--restore",
		"--help",
	} {
		if !strings.Contains(string(threadSkill), expected) {
			t.Fatalf("thread SKILL.md does not contain %q", expected)
		}
	}
	for _, name := range []string{"archive-thread.mjs", "read-tmux-lines.mjs"} {
		info, err := os.Stat(filepath.Join(threadsPath, "scripts", name))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode()&0o111 == 0 {
			t.Fatalf("%s mode = %v, want executable", name, info.Mode())
		}
	}

	if err := os.WriteFile(filepath.Join(status.Path, "SKILL.md"), []byte("modified"), 0o644); err != nil {
		t.Fatal(err)
	}
	status, err = installer.status()
	if err != nil {
		t.Fatal(err)
	}
	if !status.Installed || status.UpToDate {
		t.Fatalf("modified skill status = %#v", status)
	}
	status, err = installer.install()
	if err != nil {
		t.Fatal(err)
	}
	if !status.UpToDate {
		t.Fatalf("reinstalled skill status = %#v", status)
	}
}

func TestBundledSkillCommonHelpersAreGenerated(t *testing.T) {
	root := "agent-skill"
	shared, err := os.ReadFile(filepath.Join(root, "common.shared.mjs"))
	if err != nil {
		t.Fatal(err)
	}
	for _, item := range []struct {
		template string
		target   string
	}{
		{template: "common.processes.mjs.tmpl", target: "dire-mux-processes/scripts/common.mjs"},
		{template: "common.threads.mjs.tmpl", target: "dire-mux-threads/scripts/common.mjs"},
	} {
		t.Run(item.target, func(t *testing.T) {
			template, err := os.ReadFile(filepath.Join(root, item.template))
			if err != nil {
				t.Fatal(err)
			}
			const marker = "/* DIRE_MUX_SHARED_COMMON */"
			if strings.Count(string(template), marker) != 1 {
				t.Fatalf("%s must contain the shared marker exactly once", item.template)
			}
			body := strings.Replace(
				string(template),
				marker,
				"// BEGIN SHARED COMMON\n"+strings.TrimSpace(string(shared))+"\n// END SHARED COMMON",
				1,
			)
			expected := "// Code generated by generate-common.mjs; DO NOT EDIT.\n\n" + strings.TrimSpace(body) + "\n"
			actual, err := os.ReadFile(filepath.Join(root, item.target))
			if err != nil {
				t.Fatal(err)
			}
			if string(actual) != expected {
				t.Fatalf("%s is stale; run go generate ./internal/server", item.target)
			}
		})
	}
}

func TestBundledArchiveThreadHelper(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not available")
	}

	type capturedRequest struct {
		method   string
		path     string
		archived bool
		bodyErr  error
	}
	requests := make(chan capturedRequest, 2)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body struct {
			Archived bool `json:"archived"`
		}
		bodyErr := json.NewDecoder(r.Body).Decode(&body)
		requests <- capturedRequest{
			method:   r.Method,
			path:     r.URL.Path,
			archived: body.Archived,
			bodyErr:  bodyErr,
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"id":         "target-thread",
			"title":      "Target thread",
			"archivedAt": "2026-07-16T00:00:00Z",
		})
	}))
	defer server.Close()

	script, err := filepath.Abs(filepath.Join("agent-skill", "dire-mux-threads", "scripts", "archive-thread.mjs"))
	if err != nil {
		t.Fatal(err)
	}
	runHelper := func(endpoint string, args ...string) string {
		t.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		command := exec.CommandContext(ctx, node, append([]string{script}, args...)...)
		command.Env = append(os.Environ(),
			"DIRE_MUX_THREAD_ENDPOINT="+endpoint,
			"DIRE_MUX_PROJECT_ID=",
			"DIRE_MUX_THREAD_ID=",
		)
		output, runErr := command.CombinedOutput()
		if ctx.Err() != nil {
			t.Fatalf("archive helper timed out: %v", ctx.Err())
		}
		if runErr != nil {
			t.Fatalf("archive helper failed: %v\n%s", runErr, output)
		}
		return string(output)
	}

	endpoint := server.URL + "/api/projects/current-project/threads/current-thread"
	if output := runHelper(endpoint, "target-thread"); !strings.Contains(output, `"id": "target-thread"`) {
		t.Fatalf("archive helper output = %q", output)
	}
	archived := <-requests
	if archived.bodyErr != nil {
		t.Fatal(archived.bodyErr)
	}
	if archived.method != http.MethodPatch || archived.path != "/api/projects/current-project/threads/target-thread" || !archived.archived {
		t.Fatalf("archive request = %#v", archived)
	}

	runHelper(endpoint, "target-thread", "--restore", "--project", "other-project")
	restored := <-requests
	if restored.bodyErr != nil {
		t.Fatal(restored.bodyErr)
	}
	if restored.method != http.MethodPatch || restored.path != "/api/projects/other-project/threads/target-thread" || restored.archived {
		t.Fatalf("restore request = %#v", restored)
	}

	help := runHelper("", "--help")
	for _, expected := range []string{"Usage:", "--restore", "--project <project-id>", "retention period"} {
		if !strings.Contains(help, expected) {
			t.Fatalf("archive helper help does not contain %q: %s", expected, help)
		}
	}
}

func TestAgentSkillSettingsHandlers(t *testing.T) {
	server := &Server{agentSkills: newAgentSkillInstaller(filepath.Join(t.TempDir(), "skills"))}

	response := httptest.NewRecorder()
	server.getAgentSkillStatus(response, httptest.NewRequest(http.MethodGet, "/api/settings/agent-skills", nil))
	if response.Code != http.StatusOK {
		t.Fatalf("status response = %d: %s", response.Code, response.Body.String())
	}
	var status agentSkillStatus
	if err := json.NewDecoder(response.Body).Decode(&status); err != nil {
		t.Fatal(err)
	}
	if status.Installed {
		t.Fatalf("unexpected status: %#v", status)
	}

	response = httptest.NewRecorder()
	server.installAgentSkill(response, httptest.NewRequest(http.MethodPost, "/api/settings/agent-skills", nil))
	if response.Code != http.StatusOK {
		t.Fatalf("install response = %d: %s", response.Code, response.Body.String())
	}
	if err := json.NewDecoder(response.Body).Decode(&status); err != nil {
		t.Fatal(err)
	}
	if !status.Installed || !status.UpToDate {
		t.Fatalf("unexpected installed status: %#v", status)
	}
}

func TestAgentSkillInstallerRejectsSymlinkDestination(t *testing.T) {
	for _, name := range bundledAgentSkillNames {
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			skillsDirectory := filepath.Join(root, "skills")
			if err := os.MkdirAll(skillsDirectory, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(t.TempDir(), filepath.Join(skillsDirectory, name)); err != nil {
				t.Fatal(err)
			}
			if _, err := newAgentSkillInstaller(skillsDirectory).install(); err == nil {
				t.Fatal("expected symlink destination to be rejected")
			}
		})
	}
}
