import { complete } from "@earendil-works/pi-ai/compat";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const markerType = "kiwi-code-thread-title";
const provider = "openai-codex";
const modelId = "gpt-5.6-luna";
const timeoutMs = 60_000;

type UpdatedThread = {
	title?: unknown;
};

function hasUserMessage(ctx: ExtensionContext): boolean {
	return ctx.sessionManager.getBranch().some((entry) => {
		if (entry.type === "custom" && entry.customType === markerType) return true;
		return entry.type === "message" && entry.message.role === "user";
	});
}

function cleanTitle(value: string): string {
	let title = value
		.split("\n")
		.map((line) => line.trim())
		.find(Boolean) ?? "";
	title = title
		.replace(/^#+\s*/, "")
		.replace(/^title\s*:\s*/i, "")
		.replace(/^[`"'“”‘’]+|[`"'“”‘’]+$/g, "")
		.replace(/\s+/g, " ")
		.replace(/[.:;,!]+$/, "")
		.trim();
	return Array.from(title).slice(0, 80).join("").trim();
}

function titlePrompt(firstMessage: string): string {
	return [
		"Create a concise title for a software-development work thread from the user's first message.",
		"Return only the title: no quotes, markdown, label, explanation, or trailing punctuation.",
		"Use 3 to 7 words and at most 60 characters. Describe the concrete task, not the conversation.",
		"",
		"<first-message>",
		firstMessage.trim() || "The user sent an image without accompanying text.",
		"</first-message>",
	].join("\n");
}

export default function (pi: ExtensionAPI) {
	let handled = false;
	let controller: AbortController | undefined;

	pi.on("session_start", (_event, ctx) => {
		// Child threads are named explicitly by the parent that creates them.
		// Avoid spending a second model call or replacing that orchestration name.
		handled = Boolean(process.env.KIWI_CODE_PARENT_THREAD_ID) || hasUserMessage(ctx);
	});

	pi.on("before_agent_start", (event, ctx) => {
		const endpoint = process.env.KIWI_CODE_THREAD_ENDPOINT;
		if (handled || !endpoint) return;
		handled = true;

		const requestController = new AbortController();
		controller = requestController;
		const timeout = setTimeout(() => requestController.abort(), timeoutMs);
		void (async () => {
			const model = ctx.modelRegistry.find(provider, modelId);
			if (!model) throw new Error(`${provider}/${modelId} is unavailable`);

			const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
			if (!auth.ok) throw new Error(auth.error);
			if (!auth.apiKey) throw new Error(`No credentials for ${provider}/${modelId}`);

			const response = await complete(
				model,
				{
					messages: [{
						role: "user",
						content: [{ type: "text", text: titlePrompt(event.prompt) }],
						timestamp: Date.now(),
					}],
				},
				{
					apiKey: auth.apiKey,
					headers: auth.headers,
					env: auth.env,
					maxTokens: 256,
					reasoningEffort: "low",
					signal: requestController.signal,
				},
			);

			const title = cleanTitle(response.content
				.filter((part): part is { type: "text"; text: string } => part.type === "text")
				.map((part) => part.text)
				.join("\n"));
			if (!title) throw new Error("The title model returned an empty title");

			const updateResponse = await fetch(endpoint, {
				method: "PATCH",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ title, autoGenerated: true }),
				signal: requestController.signal,
			});
			if (!updateResponse.ok) {
				const detail = await updateResponse.text();
				throw new Error(`Kiwi Code returned ${updateResponse.status}${detail ? `: ${detail}` : ""}`);
			}
			const updated = await updateResponse.json() as UpdatedThread;
			const savedTitle = typeof updated.title === "string" ? updated.title : title;
			pi.setSessionName(savedTitle);
			pi.appendEntry(markerType, { title: savedTitle });
		})().catch((reason) => {
			if (requestController.signal.aborted) return;
			const message = reason instanceof Error ? reason.message : String(reason);
			if (ctx.hasUI) ctx.ui.notify(`Could not name thread: ${message}`, "warning");
		}).finally(() => {
			clearTimeout(timeout);
			if (controller === requestController) controller = undefined;
		});
	});

	pi.on("session_shutdown", () => {
		controller?.abort();
		controller = undefined;
	});
}
