package server

import (
	"sync"
	"time"
)

const browserStreamStateInvalidationInterval = 100 * time.Millisecond

type stateInvalidation struct {
	topic     string
	projectID string
	threadID  string
}

// stateChangeBroker is a latest-state wakeup source, not an event log. Each
// subscriber owns a depth-one signal, so mutation bursts collapse while a
// handler recomputes its authoritative snapshot.
type stateChangeBroker struct {
	mu          sync.Mutex
	subscribers map[*stateChangeSubscription]struct{}
}

type stateChangeSubscription struct {
	broker    *stateChangeBroker
	topics    map[string]struct{}
	projectID string
	threadID  string
	wake      chan struct{}
	once      sync.Once
}

// browserStateInvalidationThrottle bounds status refresh work generated by a
// high-frequency interactive stream. The first input in each interval arms
// one refresh per thread; later inputs share it rather than resetting the
// timer, so continuous pointer movement cannot postpone refresh indefinitely.
type browserStateInvalidationThrottle struct {
	mu      sync.Mutex
	pending map[threadStatusKey]*time.Timer
}

func newStateChangeBroker() *stateChangeBroker {
	return &stateChangeBroker{
		subscribers: make(map[*stateChangeSubscription]struct{}),
	}
}

func (b *stateChangeBroker) subscribe(projectID, threadID string, topics ...string) *stateChangeSubscription {
	subscription := &stateChangeSubscription{
		broker:    b,
		topics:    make(map[string]struct{}, len(topics)),
		projectID: projectID,
		threadID:  threadID,
		wake:      make(chan struct{}, 1),
	}
	for _, topic := range topics {
		subscription.topics[topic] = struct{}{}
	}
	b.mu.Lock()
	b.subscribers[subscription] = struct{}{}
	b.mu.Unlock()
	return subscription
}

func (b *stateChangeBroker) publish(change stateInvalidation) {
	b.mu.Lock()
	defer b.mu.Unlock()
	for subscription := range b.subscribers {
		if !subscription.matches(change) {
			continue
		}
		select {
		case subscription.wake <- struct{}{}:
		default:
		}
	}
}

func (s *stateChangeSubscription) matches(change stateInvalidation) bool {
	if _, subscribed := s.topics[change.topic]; !subscribed {
		return false
	}
	if change.projectID != "" && change.projectID != s.projectID {
		return false
	}
	return change.threadID == "" || change.threadID == s.threadID
}

func (s *stateChangeSubscription) Events() <-chan struct{} {
	return s.wake
}

func (s *stateChangeSubscription) Close() {
	s.once.Do(func() {
		s.broker.mu.Lock()
		delete(s.broker.subscribers, s)
		s.broker.mu.Unlock()
	})
}

func (s *Server) notifyStateChanged(topic, projectID, threadID string) {
	if s == nil || s.stateChanges == nil {
		return
	}
	s.stateChanges.publish(stateInvalidation{
		topic: topic, projectID: projectID, threadID: threadID,
	})
}

func (s *Server) scheduleBrowserStateChanged(projectID, threadID string) {
	if s == nil {
		return
	}
	key := threadStatusKey{projectID: projectID, threadID: threadID}
	throttle := &s.browserStateInvalidations
	throttle.mu.Lock()
	if throttle.pending == nil {
		throttle.pending = make(map[threadStatusKey]*time.Timer)
	}
	if _, exists := throttle.pending[key]; exists {
		throttle.mu.Unlock()
		return
	}
	throttle.pending[key] = time.AfterFunc(browserStreamStateInvalidationInterval, func() {
		throttle.mu.Lock()
		delete(throttle.pending, key)
		throttle.mu.Unlock()
		s.notifyBrowserStateChanged(projectID, threadID)
	})
	throttle.mu.Unlock()
}

func (s *Server) subscribeStateChanges(
	projectID string,
	threadID string,
	topics ...string,
) (*stateChangeSubscription, <-chan struct{}) {
	if s == nil || s.stateChanges == nil {
		return nil, nil
	}
	subscription := s.stateChanges.subscribe(projectID, threadID, topics...)
	return subscription, subscription.Events()
}
