package server

import (
	"sync"
	"time"

	"github.com/dire-kiwi/kiwi-code/internal/events"
	"github.com/dire-kiwi/kiwi-code/internal/thread"
)

const browserStreamStateInvalidationInterval = 100 * time.Millisecond

// Aliases while the HTTP layer migrates to the events package directly.
type (
	stateChangeBroker       = events.Bus
	stateChangeSubscription = events.Subscription
)

func newStateChangeBroker() *stateChangeBroker {
	return events.NewBus()
}

// browserStateInvalidationThrottle bounds status refresh work generated by a
// high-frequency interactive stream. The first input in each interval arms
// one refresh per thread; later inputs share it rather than resetting the
// timer, so continuous pointer movement cannot postpone refresh indefinitely.
type browserStateInvalidationThrottle struct {
	mu      sync.Mutex
	pending map[threadStatusKey]*time.Timer
}

func (s *Server) notifyStateChanged(topic, projectID, threadID string) {
	if s == nil || s.stateChanges == nil {
		return
	}
	s.stateChanges.Publish(events.Invalidation{
		Topic: topic,
		Key:   thread.Key{ProjectID: projectID, ThreadID: threadID},
	})
}

func (s *Server) scheduleBrowserStateChanged(projectID, threadID string) {
	if s == nil {
		return
	}
	key := threadStatusKey{ProjectID: projectID, ThreadID: threadID}
	throttle := &s.browserStateInvalidations
	throttle.mu.Lock()
	if throttle.pending == nil {
		throttle.pending = make(map[threadStatusKey]*time.Timer)
	}
	if _, exists := throttle.pending[key]; exists {
		throttle.mu.Unlock()
		return
	}
	throttle.pending[key] = time.AfterFunc(browserStreamStateInvalidationInterval, func() {
		throttle.mu.Lock()
		delete(throttle.pending, key)
		throttle.mu.Unlock()
		s.notifyBrowserStateChanged(projectID, threadID)
	})
	throttle.mu.Unlock()
}

func (s *Server) subscribeStateChanges(
	projectID string,
	threadID string,
	topics ...string,
) (*stateChangeSubscription, <-chan struct{}) {
	if s == nil || s.stateChanges == nil {
		return nil, nil
	}
	subscription := s.stateChanges.Subscribe(
		thread.Key{ProjectID: projectID, ThreadID: threadID},
		topics...,
	)
	return subscription, subscription.Events()
}
