// Code generated by generate-common.mjs; DO NOT EDIT.

const threadEndpoint = process.env.KIWI_CODE_THREAD_ENDPOINT?.replace(/\/+$/, "");

// BEGIN SHARED COMMON
export function usage(message) {
  if (message) console.error(message);
  process.exitCode = 2;
}

async function requestURL(url, init = {}) {
  const response = await fetch(url, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init.headers,
    },
  });

  if (!response.ok) {
    let message = `Kiwi Code API request failed (${response.status})`;
    try {
      const body = await response.json();
      if (typeof body?.error === "string" && body.error) message = body.error;
    } catch {
      // Keep the HTTP status fallback.
    }
    throw new Error(message);
  }

  if (response.status === 204) return undefined;
  return response.json();
}

export function print(value) {
  if (value !== undefined) console.log(JSON.stringify(value, null, 2));
}

export function run(main) {
  Promise.resolve()
    .then(main)
    .catch((error) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    });
}
// END SHARED COMMON

export function processApi(path = "") {
  if (!threadEndpoint) {
    throw new Error("KIWI_CODE_THREAD_ENDPOINT is not set. Run this helper from a Kiwi Code agent session.");
  }
  return `${threadEndpoint}/processes${path}`;
}

export function request(path = "", init = {}) {
  return requestURL(processApi(path), init);
}
