#!/usr/bin/env node
import {
  currentProjectId,
  print,
  readOption,
  rejectUnknownOptions,
  request,
  run,
  threadPath,
  usage,
} from "./common.mjs";

run(async () => {
  const args = process.argv.slice(2);
  const projectId = currentProjectId(readOption(args, "--project") || "");
  rejectUnknownOptions(args);
  const threadId = args.shift();
  const title = args.join(" ").trim();
  if (!threadId || !title) {
    usage("Usage: rename-thread.mjs <thread-id> <new-title> [--project <project-id>]");
    return;
  }

  print(await request(threadPath(projectId, threadId), {
    method: "PATCH",
    body: JSON.stringify({ title, autoGenerated: false }),
  }));
});
